---
version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:448049821673:task-definition/spring-taskdef:1"
        LoadBalancerInfo:
          ContainerName: "newone"
          ContainerPort: 8080
